# Generated by Django 5.0.2 on 2024-05-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_name', models.CharField(max_length=120)),
                ('opening_moves', models.IntegerField()),
                ('opening_sequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='YourRepertiore',
            fields=[
                ('youropening_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='OpeningApp.youropening')),
                ('repertiore_moves', models.IntegerField()),
                ('repertiore_sequence', models.CharField(max_length=120)),
            ],
            bases=('OpeningApp.youropening',),
        ),
    ]
